// <auto-generated />
using Chazan.GamesCatalog.DAOSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAOSQL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230105090600_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("Chazan.GamesCatalog.DAOSQL.DO.Game", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("ProducerImplName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.HasIndex("ProducerImplName");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Chazan.GamesCatalog.DAOSQL.DO.Producer", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("Chazan.GamesCatalog.DAOSQL.DO.Game", b =>
                {
                    b.HasOne("Chazan.GamesCatalog.DAOSQL.DO.Producer", "ProducerImpl")
                        .WithMany()
                        .HasForeignKey("ProducerImplName");

                    b.Navigation("ProducerImpl");
                });
#pragma warning restore 612, 618
        }
    }
}
